[package]
name = "miku-monitor"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/chordtoll/miku-monitor"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
